version: "1.0"
services:
  bot_service:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    restart: always
    volumes:
      - ../app:/app
    environment:
      - HOST=0.0.0.0
      - PORT=5001
      - MODEL_PATH=Eka-Korn/distillbert-qa-tuned-lora_1.01_v2
      - BOT_TOKEN=<PLACE HERE>
    ports:
      - 5001:5001
